server:
  port: 8081
  
portal:
  clientType: feignClient
  
spring:
  application:
    name: portal
  profiles:
    active: default
  cloud:
    config:
      enabled: true
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/oauth/user